//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITequipment
    {
        public int id { get; set; }
        public string equip_no { get; set; }
        public string dept_id { get; set; }
        public string dept_1 { get; set; }
        public string dept_2 { get; set; }
        public string dept_3 { get; set; }
        public string username { get; set; }
        public string vedio { get; set; }
        public string cpu { get; set; }
        public string memory { get; set; }
        public string hd { get; set; }
        public string ip_new { get; set; }
        public string ip { get; set; }
        public string sn { get; set; }
        public string @class { get; set; }
        public string type { get; set; }
        public string belong { get; set; }
        public string memo { get; set; }
        public string locate { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> startuse { get; set; }
        public Nullable<decimal> repair { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
